#!/bin/bash

scripts=*.sh

echo Running scripts: ${scripts}
echo " "

for s in ${scripts}; do
    while qstat|grep large; do
	sleep 10
        clear
        echo Waiting for dash to be free in order to run ${s} uncontended...
    done

    echo Running job ${s}
    exec qsub ${s}
    sleep 10
done

if [ -z $1 ]; then
    dirname=`date +%Y.%m.%d_%H.%M.%S`
else
    dirname=$1
fi

echo Moving output files to output/${dirname}/
mkdir output/${dirname}
mkdir output/${dirname}/stderr

mv run_*.o* output/${dirname}
mv run_*.e* output/${dirname}/stderr
