#!/bin/bash

scripts=*.sh

echo Running scripts: ${scripts}
echo " "

for s in ${scripts}; do
    echo Waiting for dash to be free...
    while true; do
        if ! qstat |grep large > /dev/null; then
            break;
        fi
        sleep 10
    done

    echo Running job ${s}
    exec qsub ${s}
done

dirname=`date +%Y.%m.%d_%H.%M.%S`
echo Moving output files to output/${dirname}/
mkdir output/${dirname}
mkdir output/${dirname}/stderr

mv run_*.o* output/${dirname}
mv run_*.e* output/${dirname}/stderr
